#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
# Use Daphne for WebSocket support instead of Django's development server
exec daphne -b 0.0.0.0 -p 8000 config.asgi:application
