# Generated by Django 4.2.3 on 2025-10-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
