# Generated by Django 4.2.3 on 2025-10-18 17:25

from django.db import migrations, models
import django.db.models.deletion
from datetime import date


def clear_availability_data(apps, schema_editor):
    """
    Clear all existing availability data since we're changing the structure
    """
    Availability = apps.get_model('managers', 'Availability')
    Availability.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("managers", "0002_team_is_active_teammember_is_active"),
    ]

    operations = [
        # Clear existing availability data first to avoid conflicts
        migrations.RunPython(clear_availability_data, migrations.RunPython.noop),
        
        # Remove old fields from Availability
        migrations.RemoveField(
            model_name='availability',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='is_hard_block',
        ),
        
        # Add new fields to Availability (allowing null initially)
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='reason',
            field=models.CharField(blank=True, help_text="Reason for unavailability (e.g., 'PTO', 'Sick leave')", max_length=255),
        ),
        migrations.AddField(
            model_name='availability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # Make date field non-null now that we've cleared the data
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(),
        ),
        
        # Update the unique constraint
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('user', 'date')},
        ),
        
        # Add fields to Slot model
        migrations.AddField(
            model_name='slot',
            name='is_covered',
            field=models.BooleanField(default=False, help_text='True if the slot is covered by an assigned member'),
        ),
        migrations.AddField(
            model_name='slot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # Add ordering to Slot model
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'availabilities'},
        ),
    ]
