#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

python /app/manage.py migrate


# Use Daphne for WebSocket support in production
# For better performance, you could also use: gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker
exec daphne -b 0.0.0.0 -p 5000 config.asgi:application
